// 상수 데이터

// 랜덤 도구 목록 (path 이식 SEO: 같은 도메인으로 집중, trailing slash로 디렉터리 인덱스 일치)
const TOOLS_BASE = "https://funnyfunny.cloud/tools";
export const randomTools = [
  `${TOOLS_BASE}/today/`,
  `${TOOLS_BASE}/todo/`,
  `${TOOLS_BASE}/random/`,
  `${TOOLS_BASE}/rest/`,
  `${TOOLS_BASE}/dailycheck/`,
  `${TOOLS_BASE}/coffee/`,
  `${TOOLS_BASE}/dream/`,
  `${TOOLS_BASE}/video/`,
  `${TOOLS_BASE}/file/`,
  `${TOOLS_BASE}/meta/`,
  `${TOOLS_BASE}/ocr/`,
  `${TOOLS_BASE}/imtranslate/`,
  `${TOOLS_BASE}/charcount/`,
  `${TOOLS_BASE}/qrcode/`,
  `${TOOLS_BASE}/datecalc/`,
  `${TOOLS_BASE}/loancalc/`,
  `${TOOLS_BASE}/electric/`,
  `${TOOLS_BASE}/platformfee/`,
  `${TOOLS_BASE}/severance/`,
  `${TOOLS_BASE}/vat/`,
  `${TOOLS_BASE}/gas/`,
  `${TOOLS_BASE}/saving/`,
  `${TOOLS_BASE}/exchange/`,
  `${TOOLS_BASE}/unit/`,
  `${TOOLS_BASE}/savings-goal/`,
  `${TOOLS_BASE}/salary-tax/`,
  `${TOOLS_BASE}/yield/`,
  `${TOOLS_BASE}/age-now/`,
  `${TOOLS_BASE}/discount/`,
  `${TOOLS_BASE}/bmi-check/`,
  `${TOOLS_BASE}/wage/`,
  `${TOOLS_BASE}/dsr/`,
  `${TOOLS_BASE}/tip/`,
  `${TOOLS_BASE}/annual-leave/`,
  `${TOOLS_BASE}/moving/`,
  `${TOOLS_BASE}/tdee/`,
  `${TOOLS_BASE}/rent/`,
  `${TOOLS_BASE}/realtor-fee/`,
  `${TOOLS_BASE}/parking/`,
  `${TOOLS_BASE}/standard-weight/`,
  `${TOOLS_BASE}/installment/`,
  `${TOOLS_BASE}/unemployment/`,
  `${TOOLS_BASE}/unit-price/`,
  `${TOOLS_BASE}/parental-leave/`,
  `${TOOLS_BASE}/pension-monthly/`,
  `${TOOLS_BASE}/compare/`,
  `${TOOLS_BASE}/tax-refund/`,
  `${TOOLS_BASE}/weekly-rest/`,
  `${TOOLS_BASE}/inflation/`,
  `${TOOLS_BASE}/leave-balance/`,
  `${TOOLS_BASE}/debt-ratio/`,
  `${TOOLS_BASE}/savings-rate/`,
  `${TOOLS_BASE}/real-rate/`,
  `${TOOLS_BASE}/beauty/`,
  `${TOOLS_BASE}/cosmetics/`,
  `${TOOLS_BASE}/year/`,
  `${TOOLS_BASE}/energy/`,
  `${TOOLS_BASE}/money/`,
  `${TOOLS_BASE}/specific/`,
  `${TOOLS_BASE}/invest/`,
  `${TOOLS_BASE}/life/`,
  `${TOOLS_BASE}/ego/`,
  `${TOOLS_BASE}/senseyear/`,
  `${TOOLS_BASE}/alcohol/`,
  `${TOOLS_BASE}/lazy/`,
  `${TOOLS_BASE}/drain/`,
  `${TOOLS_BASE}/maldives/`,
  `${TOOLS_BASE}/bit/`,
  `${TOOLS_BASE}/next/`,
  `${TOOLS_BASE}/house/`,
  `${TOOLS_BASE}/space/`,
  `${TOOLS_BASE}/edu/`,
  `${TOOLS_BASE}/baby/`,
  `${TOOLS_BASE}/miracle/`,
  `${TOOLS_BASE}/n/`,
  `${TOOLS_BASE}/nospend/`,
  `${TOOLS_BASE}/waste/`,
  `${TOOLS_BASE}/health/`,
  `${TOOLS_BASE}/hairloss/`,
  `${TOOLS_BASE}/bmi/`,
  `${TOOLS_BASE}/cafe/`,
  `${TOOLS_BASE}/drink/`,
  `${TOOLS_BASE}/joke/`,
  `${TOOLS_BASE}/mental/`,
  `${TOOLS_BASE}/mind/`,
  `${TOOLS_BASE}/fortune/`,
  `${TOOLS_BASE}/soul/`,
  `${TOOLS_BASE}/wisdom/`,
  `${TOOLS_BASE}/motivate/`,
  `${TOOLS_BASE}/beat/`,
  `${TOOLS_BASE}/cook/`,
  `${TOOLS_BASE}/chef/`,
  `${TOOLS_BASE}/winter/`,
  `${TOOLS_BASE}/anju/`,
  `${TOOLS_BASE}/product/`,
  `${TOOLS_BASE}/human/`,
  `${TOOLS_BASE}/average/`,
  `${TOOLS_BASE}/pick/`,
  `${TOOLS_BASE}/audio/`,
  `${TOOLS_BASE}/music/`,
  `${TOOLS_BASE}/vocal/`,
  `${TOOLS_BASE}/run/`,
  `${TOOLS_BASE}/charm/`,
  `${TOOLS_BASE}/downy/`,
  `${TOOLS_BASE}/xmas/`,
  `${TOOLS_BASE}/hand/`,
  `${TOOLS_BASE}/soccer/`,
  `${TOOLS_BASE}/heal/`,
  `${TOOLS_BASE}/need/`,
  `${TOOLS_BASE}/image/`,
  `${TOOLS_BASE}/heic/`,
  `${TOOLS_BASE}/temple/`,
  `${TOOLS_BASE}/sleep/`,
  `${TOOLS_BASE}/balance/`,
  `${TOOLS_BASE}/lotto/`,
  `${TOOLS_BASE}/sudoku/`,
  `${TOOLS_BASE}/commute/`,
  `${TOOLS_BASE}/chat/`,
  `${TOOLS_BASE}/happy/`,
  `${TOOLS_BASE}/due-date/`,
  `${TOOLS_BASE}/interest-simple/`,
  `${TOOLS_BASE}/calorie-goal/`,
  `${TOOLS_BASE}/vacation-cost/`,
  `${TOOLS_BASE}/present-value/`,
  `${TOOLS_BASE}/daily-prorated/`,
  `${TOOLS_BASE}/target-yield/`,
  `${TOOLS_BASE}/compound-interest/`,
  `${TOOLS_BASE}/loan-remaining/`,
  `${TOOLS_BASE}/break-even/`,
  `${TOOLS_BASE}/cagr/`,
  `${TOOLS_BASE}/roi/`,
  `${TOOLS_BASE}/subscription-yearly/`,
  `${TOOLS_BASE}/fuel-cost/`,
  `${TOOLS_BASE}/emergency-fund/`,
  `${TOOLS_BASE}/mortgage-monthly/`,
  `${TOOLS_BASE}/fee-per-use/`,
  `${TOOLS_BASE}/doubling-time/`,
  `${TOOLS_BASE}/pension-lump/`,
  `${TOOLS_BASE}/child-cost/`,
  `${TOOLS_BASE}/pet-cost/`,
  `${TOOLS_BASE}/wedding-cost/`,
  `${TOOLS_BASE}/business-days/`,
  `${TOOLS_BASE}/countdown/`,
  `${TOOLS_BASE}/week-number/`,
  `${TOOLS_BASE}/add-days/`,
  `${TOOLS_BASE}/time-between/`,
  `${TOOLS_BASE}/work-hours/`,
  `${TOOLS_BASE}/meeting-cost/`,
  `${TOOLS_BASE}/age-diff/`,
  `${TOOLS_BASE}/protein-goal/`,
  `${TOOLS_BASE}/water-intake/`,
  `${TOOLS_BASE}/bmr-only/`,
  `${TOOLS_BASE}/one-rep-max/`,
  `${TOOLS_BASE}/pace-calc/`,
  `${TOOLS_BASE}/calorie-burn/`,
  `${TOOLS_BASE}/sleep-debt/`,
  `${TOOLS_BASE}/bmi-range/`,
  `${TOOLS_BASE}/ideal-weight/`,
  `${TOOLS_BASE}/body-fat-est/`,
  `${TOOLS_BASE}/coffee-yearly/`,
  `${TOOLS_BASE}/delivery-yearly/`,
  `${TOOLS_BASE}/ott-total/`,
  `${TOOLS_BASE}/gym-value/`,
  `${TOOLS_BASE}/lunch-cost/`,
  `${TOOLS_BASE}/cigarette-cost/`,
  `${TOOLS_BASE}/alcohol-monthly/`,
  `${TOOLS_BASE}/snack-cost/`,
  `${TOOLS_BASE}/phone-compare/`,
  `${TOOLS_BASE}/car-depreciation/`,
  `${TOOLS_BASE}/book-budget/`,
  `${TOOLS_BASE}/study-hours/`,
  `${TOOLS_BASE}/percent-change/`,
  `${TOOLS_BASE}/percent-of/`,
  `${TOOLS_BASE}/reverse-percent/`,
  `${TOOLS_BASE}/margin-markup/`,
  `${TOOLS_BASE}/split-percent/`,
  `${TOOLS_BASE}/tax-bracket/`,
  `${TOOLS_BASE}/allocation/`,
  `${TOOLS_BASE}/growth-rate/`,
  `${TOOLS_BASE}/area-convert/`,
  `${TOOLS_BASE}/volume-convert/`,
  `${TOOLS_BASE}/speed-convert/`,
  `${TOOLS_BASE}/data-size/`,
  `${TOOLS_BASE}/timezone-diff/`,
  `${TOOLS_BASE}/pressure-convert/`,
  `${TOOLS_BASE}/energy-convert/`,
  `${TOOLS_BASE}/loan-payoff-date/`,
  `${TOOLS_BASE}/solar-payback/`,
  `${TOOLS_BASE}/carbon-footprint/`,
  `${TOOLS_BASE}/habit-streak/`,
  `${TOOLS_BASE}/dice/`,
  `${TOOLS_BASE}/marathon-pace/`,
  `${TOOLS_BASE}/readability/`,
  `${TOOLS_BASE}/battery-life/`,
  `${TOOLS_BASE}/discount-stack/`,
  `${TOOLS_BASE}/rent-ratio/`,
  `${TOOLS_BASE}/coin-flip/`,
  `${TOOLS_BASE}/rps/`,
  `${TOOLS_BASE}/random-name/`,
  `${TOOLS_BASE}/random-number/`,
  `${TOOLS_BASE}/team-split/`,
  `${TOOLS_BASE}/spin-wheel/`,
  `${TOOLS_BASE}/card-draw/`,
  `${TOOLS_BASE}/bingo-caller/`,
  `${TOOLS_BASE}/truth-dare/`,
  `${TOOLS_BASE}/yes-no/`,
  `${TOOLS_BASE}/random-pair/`,
  `${TOOLS_BASE}/order-random/`,
  `${TOOLS_BASE}/lottery-six/`,
  `${TOOLS_BASE}/word-random/`,
  `${TOOLS_BASE}/color-random/`,
  `${TOOLS_BASE}/penalty-random/`,
  `${TOOLS_BASE}/random-first/`,
  `${TOOLS_BASE}/elimination-order/`,
  `${TOOLS_BASE}/emoji-random/`,
  `${TOOLS_BASE}/random-line/`,
  `${TOOLS_BASE}/countdown-timer/`,
  `${TOOLS_BASE}/stopwatch/`,
  `${TOOLS_BASE}/turn-timer/`,
  `${TOOLS_BASE}/scoreboard/`,
  `${TOOLS_BASE}/life-counter/`,
  `${TOOLS_BASE}/game-timer/`,
  `${TOOLS_BASE}/score-keeper/`,
  `${TOOLS_BASE}/timer-bomb/`,
  `${TOOLS_BASE}/quick-draw/`,
  `${TOOLS_BASE}/reaction-test/`,
  `${TOOLS_BASE}/dice-d20/`,
  `${TOOLS_BASE}/dice-2d6/`,
  `${TOOLS_BASE}/dice-d100/`,
  `${TOOLS_BASE}/dice-fate/`,
  `${TOOLS_BASE}/card-deck/`,
  `${TOOLS_BASE}/uno-draw/`,
  `${TOOLS_BASE}/rps-lizard-spock/`,
  `${TOOLS_BASE}/coin-flip-3/`,
  `${TOOLS_BASE}/dice-pool/`,
  `${TOOLS_BASE}/card-hand/`,
  `${TOOLS_BASE}/mafia-role/`,
  `${TOOLS_BASE}/werewolf-role/`,
  `${TOOLS_BASE}/charade-word/`,
  `${TOOLS_BASE}/pictionary-word/`,
  `${TOOLS_BASE}/secret-santa/`,
  `${TOOLS_BASE}/dinner-picker/`,
  `${TOOLS_BASE}/movie-picker/`,
  `${TOOLS_BASE}/song-random/`,
  `${TOOLS_BASE}/tier-picker/`,
  `${TOOLS_BASE}/mood-random/`,
  `${TOOLS_BASE}/nickname-gen/`,
  `${TOOLS_BASE}/couple-name/`,
  `${TOOLS_BASE}/mbti-random/`,
  `${TOOLS_BASE}/lucky-number/`,
  `${TOOLS_BASE}/fortune-cookie/`,
  `${TOOLS_BASE}/compliment-random/`,
  `${TOOLS_BASE}/excuse-generator/`,
  `${TOOLS_BASE}/decision-wheel/`,
  `${TOOLS_BASE}/bottle-spin/`,
  `${TOOLS_BASE}/random-date/`,
  `${TOOLS_BASE}/tarot-single/`,
  `${TOOLS_BASE}/horoscope-daily/`,
  `${TOOLS_BASE}/mood-ring/`,
  `${TOOLS_BASE}/random-advice/`,
  `${TOOLS_BASE}/would-you-rather/`,
  `${TOOLS_BASE}/never-have-i/`,
  `${TOOLS_BASE}/this-or-that/`,
  `${TOOLS_BASE}/random-challenge/`,
  `${TOOLS_BASE}/gratitude-pick/`,
  `${TOOLS_BASE}/hobby-suggest/`,
  `${TOOLS_BASE}/weekend-idea/`,
  `${TOOLS_BASE}/coffee-order/`,
  `${TOOLS_BASE}/workout-random/`,
  `${TOOLS_BASE}/book-suggest/`,
  `${TOOLS_BASE}/movie-genre/`,
  `${TOOLS_BASE}/korean-name/`,
  `${TOOLS_BASE}/team-name-gen/`,
  `${TOOLS_BASE}/slogan-random/`,
  `${TOOLS_BASE}/daily-quote/`,
  `${TOOLS_BASE}/emoji-combo/`,
  `${TOOLS_BASE}/first-letter/`,
  `${TOOLS_BASE}/random-food/`,
  `${TOOLS_BASE}/magic-8-ball/`,
  `${TOOLS_BASE}/pet-name-gen/`,
  `${TOOLS_BASE}/band-name-gen/`,
  `${TOOLS_BASE}/dinner-roulette/`,
  `${TOOLS_BASE}/affirmation-daily/`,
  `${TOOLS_BASE}/birth-flower/`,
  `${TOOLS_BASE}/icebreaker/`,
  `${TOOLS_BASE}/dare-random/`,
  `${TOOLS_BASE}/color-palette/`,
  `${TOOLS_BASE}/number-lucky/`,
  `${TOOLS_BASE}/conversation-starter/`,
  `${TOOLS_BASE}/recipe-roulette/`,
  `${TOOLS_BASE}/gift-idea/`,
  `${TOOLS_BASE}/date-idea/`,
  `${TOOLS_BASE}/motivation-daily/`,
  `${TOOLS_BASE}/mantra-daily/`,
  `${TOOLS_BASE}/two-truths-lie/`,
  `${TOOLS_BASE}/random-superpower/`,
  `${TOOLS_BASE}/random-country/`,
  `${TOOLS_BASE}/random-job/`,
  `${TOOLS_BASE}/tongue-twister/`,
  `${TOOLS_BASE}/riddle-daily/`,
  `${TOOLS_BASE}/roast-mild/`,
  `${TOOLS_BASE}/pep-talk/`,
  `${TOOLS_BASE}/cocktail-random/`,
  `${TOOLS_BASE}/dessert-roulette/`,
  `${TOOLS_BASE}/travel-destination/`,
  `${TOOLS_BASE}/weekend-trip/`,
  `${TOOLS_BASE}/indoor-activity/`,
  `${TOOLS_BASE}/outdoor-activity/`,
  `${TOOLS_BASE}/rainy-day/`,
  `${TOOLS_BASE}/playlist-mood/`,
  `${TOOLS_BASE}/study-tip/`,
  `${TOOLS_BASE}/sleep-tip/`,
  `${TOOLS_BASE}/focus-tip/`,
  `${TOOLS_BASE}/random-act-kindness/`,
  `${TOOLS_BASE}/self-care-idea/`,
  `${TOOLS_BASE}/gratitude-daily/`,
  `${TOOLS_BASE}/letter-to-self/`,
  `${TOOLS_BASE}/enneagram-random/`,
  `${TOOLS_BASE}/love-language/`,
  `${TOOLS_BASE}/spirit-animal/`,
  `${TOOLS_BASE}/hogwarts-house/`,
  `${TOOLS_BASE}/harry-potter-random/`,
  `${TOOLS_BASE}/kdrama-pick/`,
  `${TOOLS_BASE}/anime-pick/`,
  `${TOOLS_BASE}/podcast-genre/`,
  `${TOOLS_BASE}/writing-prompt/`,
  `${TOOLS_BASE}/drawing-prompt/`,
  `${TOOLS_BASE}/coding-project-idea/`,
  `${TOOLS_BASE}/startup-idea/`,
  `${TOOLS_BASE}/debate-topic/`,
  `${TOOLS_BASE}/question-of-day/`,
  `${TOOLS_BASE}/poll-idea/`,
  `${TOOLS_BASE}/rpg-class/`,
  `${TOOLS_BASE}/character-trait/`,
  `${TOOLS_BASE}/baby-name-ko/`,
  `${TOOLS_BASE}/wedding-vow-idea/`,
  `${TOOLS_BASE}/apology-msg/`,
  `${TOOLS_BASE}/thank-you-note/`,
  `${TOOLS_BASE}/random-recipe/`,
  `${TOOLS_BASE}/random-exercise/`,
  `${TOOLS_BASE}/random-instrument/`,
  `${TOOLS_BASE}/random-art-style/`,
  `${TOOLS_BASE}/random-plant/`,
  `${TOOLS_BASE}/random-flag/`,
  `${TOOLS_BASE}/omen-today/`,
  `${TOOLS_BASE}/lucky-charm/`,
  `${TOOLS_BASE}/zodiac-compat/`,
  `${TOOLS_BASE}/patronus-idea/`,
  `${TOOLS_BASE}/marvel-hero/`,
  `${TOOLS_BASE}/disney-character/`,
  `${TOOLS_BASE}/ghibli-character/`,
  `${TOOLS_BASE}/netflix-pick/`,
  `${TOOLS_BASE}/hashtag-random/`,
  `${TOOLS_BASE}/caption-idea/`,
  `${TOOLS_BASE}/bio-idea/`,
  `${TOOLS_BASE}/content-idea/`,
  `${TOOLS_BASE}/blog-topic/`,
  `${TOOLS_BASE}/vlog-idea/`,
  `${TOOLS_BASE}/meeting-icebreaker/`,
  `${TOOLS_BASE}/interview-question/`,
  `${TOOLS_BASE}/salary-tip/`,
  `${TOOLS_BASE}/morning-routine/`,
  `${TOOLS_BASE}/evening-routine/`,
  `${TOOLS_BASE}/habit-to-start/`,
  `${TOOLS_BASE}/bucket-list-one/`,
  `${TOOLS_BASE}/new-year-resolution/`,
  `${TOOLS_BASE}/gift-under-50/`,
  `${TOOLS_BASE}/holiday-idea/`,
  `${TOOLS_BASE}/birthday-idea/`,
  `${TOOLS_BASE}/anniversary-idea/`,
  `${TOOLS_BASE}/random-emoji-story/`,
  `${TOOLS_BASE}/random-hex/`,
  `${TOOLS_BASE}/random-question/`,
  `${TOOLS_BASE}/option-roulette/`,
  `${TOOLS_BASE}/choice-picker/`,
  `${TOOLS_BASE}/kind-message/`,
  `${TOOLS_BASE}/joke-clean/`,
];

// SEO 상위 항목
export const seoTopItems = [
  {
    name: "Local Image Optimizer & File Insights",
    url: "https://funnyfunny.cloud/tools/file/",
    description:
      "Re-encode WebP/JPEG and auto-resize with one drag. View local file info, SHA-256, and previews without uploads.",
  },
  {
    name: "Meta Kit — SEO · OG · Favicon",
    url: "https://funnyfunny.cloud/tools/meta/",
    description:
      "Generate meta tags, OG/Twitter cards, and favicons in one place, plus OG image text ready to copy.",
  },
  {
    name: "Image Merge & PDF Converter",
    url: "https://funnyfunny.cloud/tools/image/",
    description:
      "Upload multiple images, reorder by drag, and save as a single image or PDF.",
  },
  {
    name: "Image Text Extractor",
    url: "https://funnyfunny.cloud/tools/ocr/",
    description: "OCR that extracts text from photos automatically.",
  },
  {
    name: "Time Checker",
    url: "https://funnyfunny.cloud/tools/time/",
    description:
      "Accurate server time, time zone conversion, and quick time calculations.",
  },
  {
    name: "Current Weather",
    url: "https://funnyfunny.cloud/tools/weather/",
    description: "Local weather, feels-like temperature, dust, and UV info.",
  },
  {
    name: "IT News Today",
    url: "https://funnyfunny.cloud/tools/news/",
    description: "Quick summaries of domestic and global IT news.",
  },
  {
    name: "Simple Audio Editor",
    url: "https://funnyfunny.cloud/tools/audio/",
    description: "Edit audio directly in the browser.",
  },
  {
    name: "EmojiCon Studio",
    url: "https://funnyfunny.cloud/tools/emojicon/",
    description: "Create icons and favicons from a single emoji.",
  },
];

// SEO 애플리케이션 목록
export const seoApplications = [
  {
    name: "Today, Well Done",
    url: "https://funnyfunny.cloud/tools/today/",
    description:
      "Log today's wins in one line and plan a small action for tomorrow.",
    category: "ProductivityApplication",
  },
  {
    name: "Today's To-Do",
    url: "https://funnyfunny.cloud/tools/todo/",
    description: "A focused to-do list with simple completion checks.",
    category: "ProductivityApplication",
  },
  {
    name: "Dream Diary",
    url: "https://funnyfunny.cloud/tools/dream/",
    description: "A local dream journal saved in your browser with tags.",
    category: "LifestyleApplication",
  },
  {
    name: "Should I Rest Now?",
    url: "https://funnyfunny.cloud/tools/rest/",
    description: "A short survey to decide rest needs and recovery routines.",
    category: "LifestyleApplication",
  },
  {
    name: "Sleep Helper",
    url: "https://funnyfunny.cloud/tools/sleep/",
    description:
      "White noise and ambient mixes with timer and fade-out for better sleep.",
    category: "LifestyleApplication",
  },
  {
    name: "Motivation Reset",
    url: "https://funnyfunny.cloud/tools/motivate/",
    description: "Get a short line to reset your mindset and regain focus.",
    category: "LifestyleApplication",
  },
  {
    name: "Music for This Moment",
    url: "https://funnyfunny.cloud/tools/music/",
    description: "Pick a music mood that matches your time of day.",
    category: "EntertainmentApplication",
  },
  {
    name: "Cosmetics Routine Check",
    url: "https://funnyfunny.cloud/tools/cosmetics/",
    description:
      "Check your products and features to find gaps, overloads, and a minimal plan.",
    category: "LifestyleApplication",
  },
  {
    name: "Hairloss Improvement Roadmap",
    url: "https://funnyfunny.cloud/tools/hairloss/",
    description:
      "A short survey that suggests the top 3 habits to improve hair care routines.",
    category: "HealthApplication",
  },
  {
    name: "Winter Trigger Top 1",
    url: "https://funnyfunny.cloud/tools/winter/",
    description: "Identify your biggest winter drag and get recovery tips.",
    category: "LifestyleApplication",
  },
  {
    name: "Meta Kit — SEO · OG · Favicon",
    url: "https://funnyfunny.cloud/tools/meta/",
    description:
      "Generate meta tags, OG/Twitter cards, favicons, and OG text for easy copy.",
    category: "UtilityApplication",
  },
  {
    name: "Life Spending Report",
    url: "https://funnyfunny.cloud/tools/year/",
    description:
      "A 3-minute report on how you spent money, time, and emotions.",
    category: "LifestyleApplication",
  },
  {
    name: "Waste Index",
    url: "https://funnyfunny.cloud/tools/waste/",
    description: "See wasted money and time as a single score.",
    category: "LifestyleApplication",
  },
  {
    name: "Korea Average vs Me",
    url: "https://funnyfunny.cloud/tools/average/",
    description: "Compare your metrics with national averages.",
    category: "LifestyleApplication",
  },
  {
    name: "Daily Productivity Check",
    url: "https://funnyfunny.cloud/tools/product/",
    description: "Quickly check focus, energy, and decision state.",
    category: "ProductivityApplication",
  },
  {
    name: "Total Wealth of What I Didn't Buy",
    url: "https://funnyfunny.cloud/tools/nospend/",
    description: "Estimate how much you could have saved by not buying.",
    category: "FinanceApplication",
  },
  {
    name: "Asset Allocation Check",
    url: "https://funnyfunny.cloud/tools/specific/",
    description:
      "Review your mix across cash, gold, real estate, stocks, and crypto.",
    category: "FinanceApplication",
  },
  {
    name: "OTT Pick",
    url: "https://funnyfunny.cloud/tools/pick/",
    description:
      "Get instant Korean OTT movie and drama picks without searching.",
    category: "EntertainmentApplication",
  },
  {
    name: "Chef Judge: Today's Choice",
    url: "https://funnyfunny.cloud/tools/chef/",
    description: "Meme-style judging comments that help you choose fast.",
    category: "EntertainmentApplication",
  },
  {
    name: "Lotto Number Picker",
    url: "https://funnyfunny.cloud/tools/lotto/",
    description: "One-click lotto number recommendations with save support.",
    category: "EntertainmentApplication",
  },
  {
    name: "Bitcoin Regret Calculator",
    url: "https://funnyfunny.cloud/tools/bit/",
    description: "Calculate opportunity cost if you didn't buy Bitcoin.",
    category: "FinanceApplication",
  },
  {
    name: "Future Me 2026",
    url: "https://funnyfunny.cloud/tools/next/",
    description:
      "Simulate next-year routes based on habits, money, relationships, and focus.",
    category: "LifestyleApplication",
  },
  {
    name: "Missed House Opportunity",
    url: "https://funnyfunny.cloud/tools/house/",
    description: "Calculate missed gains from rising home prices.",
    category: "FinanceApplication",
  },
  {
    name: "Investment Confidence Builder",
    url: "https://funnyfunny.cloud/tools/invest/",
    description: "Record decisions to reduce volatility in judgment.",
    category: "FinanceApplication",
  },
  {
    name: "Birthrate Reality Test",
    url: "https://funnyfunny.cloud/tools/baby/",
    description:
      "A scenario-based test that frames the birthrate shift in real life.",
    category: "LifestyleApplication",
  },
  {
    name: "Better Birth Odds",
    url: "https://funnyfunny.cloud/tools/miracle/",
    description:
      "Compare birth conditions and estimate the odds of a better environment.",
    category: "LifestyleApplication",
  },
  {
    name: "Pyeong Calculator",
    url: "https://funnyfunny.cloud/tools/space/",
    description: "Convert pyeong to square meters and check typical sizes.",
    category: "UtilityApplication",
  },
  {
    name: "Split-the-Bill Calculator",
    url: "https://funnyfunny.cloud/tools/n/",
    description:
      "Enter venue, headcount, and total to calculate per-person cost.",
    category: "UtilityApplication",
  },
  {
    name: "Coffee Addiction Test",
    url: "https://funnyfunny.cloud/tools/coffee/",
    description: "A meme-style test to check caffeine dependence.",
    category: "LifestyleApplication",
  },
  {
    name: "BMI Survey Diet Plan",
    url: "https://funnyfunny.cloud/tools/bmi/",
    description:
      "A quick survey to check BMI and lifestyle patterns for a realistic plan.",
    category: "LifestyleApplication",
  },
  {
    name: "Beauty Bankruptcy Test",
    url: "https://funnyfunny.cloud/tools/beauty/",
    description: "A felt-impact calculator for beauty spending.",
    category: "LifestyleApplication",
  },
  {
    name: "People Who Drain Me Test",
    url: "https://funnyfunny.cloud/tools/human/",
    description:
      "Find the people types that drain you (not a self-evaluation).",
    category: "LifestyleApplication",
  },
  {
    name: "Simple Audio Editor",
    url: "https://funnyfunny.cloud/tools/audio/",
    description: "Trim, merge, and export audio directly in the browser.",
    category: "UtilityApplication",
  },
  {
    name: "Head Voice Trainer",
    url: "https://funnyfunny.cloud/tools/vocal/",
    description:
      "Warm up head voice with breathing, resonance, and scale routines.",
    category: "LifestyleApplication",
  },
  {
    name: "AutoCut Studio",
    url: "https://funnyfunny.cloud/tools/video/",
    description: "Detect silence and auto-create highlight/jump-cut timelines.",
    category: "UtilityApplication",
  },
  {
    name: "Image Merge & PDF Converter",
    url: "https://funnyfunny.cloud/tools/image/",
    description:
      "Upload images, reorder by drag, and export as one image or PDF.",
    category: "UtilityApplication",
  },
  {
    name: "Image Text Extractor",
    url: "https://funnyfunny.cloud/tools/ocr/",
    description: "OCR that extracts text from photos.",
    category: "UtilityApplication",
  },
  {
    name: "HEIC to JPG Converter",
    url: "https://funnyfunny.cloud/tools/heic/",
    description:
      "Convert HEIC to JPG/WebP/PNG with compression, resize, and ZIP export.",
    category: "UtilityApplication",
  },
  {
    name: "Local Image Optimizer & File Insights",
    url: "https://funnyfunny.cloud/tools/file/",
    description:
      "Re-encode and auto-resize images, plus local file info and SHA-256.",
    category: "UtilityApplication",
  },
  {
    name: "Dino Runner",
    url: "https://funnyfunny.cloud/tools/run/",
    description: "Dino runner ranking game with score submissions.",
    category: "GameApplication",
  },
  {
    name: "Charm (NEON ARCADE)",
    url: "https://funnyfunny.cloud/tools/charm/",
    description: "Switch lanes to dodge incoming missiles.",
    category: "GameApplication",
  },
  {
    name: "Downy (NEON STAIRS)",
    url: "https://funnyfunny.cloud/tools/downy/",
    description: "Step left/right on stairs; fall and it's over.",
    category: "GameApplication",
  },
  {
    name: "Daily Tetris",
    url: "https://funnyfunny.cloud/tools/tet/",
    description: "Tetris with solo AI and two-player mode.",
    category: "GameApplication",
  },
  {
    name: "Warm Gift Report",
    url: "https://funnyfunny.cloud/tools/xmas/",
    description: "Check the probability of a warm gift arrival.",
    category: "LifestyleApplication",
  },
  {
    name: "Palm Reading Story",
    url: "https://funnyfunny.cloud/tools/hand/",
    description: "Palm-line analysis from a single photo in seconds.",
    category: "LifestyleApplication",
  },
  {
    name: "Soccer Combo",
    url: "https://funnyfunny.cloud/tools/soccer/",
    description: "Combine two play styles to find the footballer you resemble.",
    category: "EntertainmentApplication",
  },
  {
    name: "Neon Pinball Random Draw",
    url: "https://funnyfunny.cloud/tools/random/",
    description: "A neon pinball game that selects random winners.",
    category: "GameApplication",
  },
  {
    name: "One-Line Fortune",
    url: "https://funnyfunny.cloud/tools/fortune/",
    description: "Pick a daily fortune line based on your mood.",
    category: "LifestyleApplication",
  },
  {
    name: "Daily Wisdom",
    url: "https://funnyfunny.cloud/tools/wisdom/",
    description: "Choose a daily line inspired by scripture.",
    category: "LifestyleApplication",
  },
  {
    name: "Maybe Not a Coincidence",
    url: "https://funnyfunny.cloud/tools/heal/",
    description: "A one-click comfort card.",
    category: "LifestyleApplication",
  },
  {
    name: "The One Line I Need",
    url: "https://funnyfunny.cloud/tools/need/",
    description: "Get a comforting line based on your emotion and situation.",
    category: "LifestyleApplication",
  },
  {
    name: "Temple Daily Quote",
    url: "https://funnyfunny.cloud/tools/temple/",
    description: "Daily lines based on Buddhist teachings in modern language.",
    category: "LifestyleApplication",
  },
];

// SEO FAQ - 언어별 FAQ 반환 함수
export function getSeoFaq(lang = "en") {
  const isKo = lang === "ko";

  return [
    {
      question: isKo
        ? "FunnyFunny Cloud는 어떤 서비스를 제공하나요?"
        : "What services does FunnyFunny Cloud provide?",
      answer: isKo
        ? "funnyfunny.cloud는 테스트와 계산기를 통해 일상적인 지출, 시간, 습관 데이터를 검토하는 데 도움을 줍니다.\n\n모든 서비스는 사용자가 자신의 패턴을 이해하고 현실적인 기준과 비교할 수 있도록 내부에서 설계 및 구축되었습니다.\n\n결과는 참고용이며 일상적인 선택과 계획을 지원하기 위한 것입니다. 사이트는 Google 정책을 준수하여 안전하고 투명하게 운영됩니다."
        : "funnyfunny.cloud helps you review everyday spending, time, and habit data through tests and calculators.\n\nAll services are designed and built in-house to help users understand their patterns and compare them against realistic benchmarks.\n\nResults are for reference only and meant to support everyday choices and planning. The site is operated safely and transparently in compliance with Google policies.",
    },
    {
      question: isKo ? "무료로 사용할 수 있나요?" : "Is it free to use?",
      answer: isKo
        ? "모든 서비스는 로그인 없이 무료로 사용할 수 있으며, 제한 없이 링크를 공유할 수 있습니다."
        : "All services are free to use without logging in, and you can share links without restrictions.",
    },
    {
      question: isKo ? "모바일 친화적인가요?" : "Is it mobile-friendly?",
      answer: isKo
        ? "네. UI는 모바일에 최적화되어 있으며, 랜덤 버튼을 통해 빠르게 시작할 수 있습니다."
        : "Yes. The UI is optimized for mobile, and the random button helps you start quickly.",
    },
    {
      question: isKo
        ? "새로운 서비스가 추가되나요?"
        : "Are new services added?",
      answer: isKo
        ? "인기 있는 주제와 트렌드에 맞춰 새로운 서비스를 정기적으로 추가하며, 전체 목록과 검색에서 확인할 수 있습니다."
        : "We regularly add new services aligned with popular topics and trends, visible in the full list and search.",
    },
  ];
}
