import { HomeContent } from "./components/HomeContent";

export const metadata = {
  title: "FunnyFunny Cloud — Services that make your day smarter",
  description:
    "FunnyFunny Cloud helps you review everyday spending, time, and habits with simple tests and calculators. Free tests, calculators, and utility tools for productivity, finance, and lifestyle.",
  alternates: { canonical: "/" },
  openGraph: {
    url: "https://funnyfunny.cloud/",
    title: "FunnyFunny Cloud — 무료 테스트·계산기·가이드",
    description: "휴식 체크, 세금·N빵·평수 계산기, BMI·자산 방탄 지수 등 무료 테스트·계산기·사용 가이드 모음.",
  },
  robots: { index: true, follow: true, googleBot: { "max-image-preview": "large" } },
  keywords: [
    "FunnyFunny",
    "FunnyFunny Cloud",
    "무료 실수령액 계산",
    "실수령액 계산",
    "4대보험 공제",
    "급여명세서 보는법",
    "Should I rest now?",
    "rest check",
    "sleep helper",
    "white noise",
    "sleep sounds",
    "future me 2026",
    "future route test",
    "habit route",
    "focus route",
    "daily productivity check",
    "daily mental stamina index",
    "coffee addiction test",
    "beauty bankruptcy",
    "life energy balance",
    "life energy leak",
    "home price calculator",
    "missed house opportunity",
    "bitcoin calculator",
    "bitcoin regret",
    "asset shield index",
    "total wealth of what I didn't buy",
    "cafe spending reversal",
    "how much that drink costs now",
    "healthspan",
    "BMI",
    "BMI diet plan",
    "laziness diagnostic",
    "alcohol MBTI",
    "Maldives match",
    "private education hell map",
    "life time dashboard",
    "Korea average vs me",
    "dad jokes",
    "mindfulness",
    "what to eat today",
    "today's snack",
    "people who drain me test",
    "SoulPrint",
    "birth data personality analysis",
    "birth-year vibe test",
    "EGO test",
    "what to watch on OTT",
    "Simple Audio Editor",
    "EmojiCon Studio",
    "AutoCut Studio",
    "image merge",
    "image combine",
    "daily wisdom",
    "the one line I need",
    "Daily Wisdom",
    "today to-do",
    "today todo",
    "one line scripture",
    "dream diary",
    "PDF converter",
    "image merge & PDF",
    "HWPX text extractor",
    "HWPX to PDF",
    "mood check",
    "mood tracker",
    "auto video editing",
    "jump-cut editor",
    "silence remover",
    "SnapTrail",
    "Meta Kit",
    "booking timing",
    "chef judge",
    "today's choice judge",
    "judge meme",
    "quick pick",
    "IT news today",
    "current weather",
    "D-day calculator",
    "runner game",
    "Charm dodge game",
    "Downy NEON STAIRS",
    "drum beat trainer",
    "waste index",
    "winter top 1",
  ],
};

export default function HomePage() {
  return <HomeContent />;
}
