import { HomeContent } from "./components/HomeContent";

export const metadata = {
  title: "FunnyFunny Cloud — 하루를 더 똑똑하게 만드는 서비스",
  description:
    "퍼니퍼니(FunnyFunny) funnyfunny.cloud는 일상의 소비, 시간, 습관과 같은 데이터를 테스트와 계산기로 쉽게 점검·비교해 볼 수 있는 정보 서비스입니다.",
  keywords: [
    "퍼니퍼니",
    "퍼니퍼니 클라우드",
    "2026년의 나",
    "미래 루트 테스트",
    "습관 루트",
    "집중력 루트",
    "하루 생산성 체크 테스트",
    "하루 정신 체력 지수 테스트",
    "커피 중독 테스트",
    "꾸밈비 파산",
    "내 삶의 에너지 배분",
    "인생 에너지 누수 진단기",
    "집값 계산기",
    "집 못 산 죄",
    "비트코인 계산기",
    "비트코인 안 산 죄",
    "자산 방탄 지수",
    "내가 안 산 것들의 총자산",
    "카페 지출 역전 계산",
    "그때 마신 술 지금 얼마",
    "건강수명",
    "귀찮음 진단기",
    "주량 MBTI",
    "몰디브 매치",
    "사교육 지옥도",
    "인생 시간",
    "대한민국 평균 vs 나",
    "아재개그",
    "마음챙김",
    "오늘 뭐 먹지",
    "오늘의 안주",
    "나를 힘들게 하는 인간 유형 테스트",
    "SoulPrint",
    "출생 정보 성향 분석",
    "나는 몇 년생 감성인가",
    "EGO 테스트",
    "오늘 뭐 볼까 OTT",
    "Simple Audio Editor",
    "EmojiCon Studio",
    "AutoCut Studio",
    "이미지 합치기",
    "이미지 병합",
    "오늘의 지혜",
    "Daily Wisdom",
    "성경 한 문장",
    "PDF 변환",
    "이미지 합치기 & PDF 변환",
    "영상 자동 편집",
    "점프컷 편집기",
    "침묵 제거 편집기",
    "SnapTrail",
    "Meta Kit",
    "예매는타이밍",
    "오늘의 IT 뉴스",
    "지금날씨",
    "D-day 계산기",
    "달리기 게임",
    "참참참 게임",
    "다우니 NEON STAIRS",
    "드럼 비트 연습기",
    "내 인생 낭비력 지수",
    "이번 겨울, 나를 망치는 것 TOP 1",
  ],
};

export default function HomePage() {
  return <HomeContent />;
}
